AllCops:
  TargetRubyVersion: 2.5+
Naming/FileName:
  Exclude:
    - 'lib/rb-net_http-client.rb'
Documentation:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: unannotated
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Metrics/LineLength:
  Max: 250
Metrics/MethodLength:
  Max: 100
Metrics/BlockLength:
  Max: 50
Metrics/ClassLength:
  Max: 500
Metrics/ModuleLength:
  Max: 500
Metrics/AbcSize:
  Max: 200
Metrics/PerceivedComplexity:
  Max: 15
Metrics/CyclomaticComplexity:
  Max: 15
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
